// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../mocks/book_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	book "gotus/internal/model/book"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBookRepository is a mock of BookRepository interface.
type MockBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryMockRecorder
	isgomock struct{}
}

// MockBookRepositoryMockRecorder is the mock recorder for MockBookRepository.
type MockBookRepositoryMockRecorder struct {
	mock *MockBookRepository
}

// NewMockBookRepository creates a new mock instance.
func NewMockBookRepository(ctrl *gomock.Controller) *MockBookRepository {
	mock := &MockBookRepository{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRepository) EXPECT() *MockBookRepositoryMockRecorder {
	return m.recorder
}

// DeleteBookByISBN mocks base method.
func (m *MockBookRepository) DeleteBookByISBN(isbn string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookByISBN", isbn)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DeleteBookByISBN indicates an expected call of DeleteBookByISBN.
func (mr *MockBookRepositoryMockRecorder) DeleteBookByISBN(isbn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookByISBN", reflect.TypeOf((*MockBookRepository)(nil).DeleteBookByISBN), isbn)
}

// FindBookByISBN mocks base method.
func (m *MockBookRepository) FindBookByISBN(isbn string) (*book.Book, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBookByISBN", isbn)
	ret0, _ := ret[0].(*book.Book)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FindBookByISBN indicates an expected call of FindBookByISBN.
func (mr *MockBookRepositoryMockRecorder) FindBookByISBN(isbn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBookByISBN", reflect.TypeOf((*MockBookRepository)(nil).FindBookByISBN), isbn)
}

// GetBooks mocks base method.
func (m *MockBookRepository) GetBooks() ([]*book.Book, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooks")
	ret0, _ := ret[0].([]*book.Book)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetBooks indicates an expected call of GetBooks.
func (mr *MockBookRepositoryMockRecorder) GetBooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooks", reflect.TypeOf((*MockBookRepository)(nil).GetBooks))
}

// StoreBook mocks base method.
func (m *MockBookRepository) StoreBook(b *book.Book) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StoreBook", b)
}

// StoreBook indicates an expected call of StoreBook.
func (mr *MockBookRepositoryMockRecorder) StoreBook(b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBook", reflect.TypeOf((*MockBookRepository)(nil).StoreBook), b)
}

// UpdateBookByISBN mocks base method.
func (m *MockBookRepository) UpdateBookByISBN(isbn string, updatedBook *book.Book) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookByISBN", isbn, updatedBook)
	ret0, _ := ret[0].(bool)
	return ret0
}

// UpdateBookByISBN indicates an expected call of UpdateBookByISBN.
func (mr *MockBookRepositoryMockRecorder) UpdateBookByISBN(isbn, updatedBook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookByISBN", reflect.TypeOf((*MockBookRepository)(nil).UpdateBookByISBN), isbn, updatedBook)
}