// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../mocks/book_instance_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	book "gotus/internal/model/book"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBookInstanceRepository is a mock of BookInstanceRepository interface.
type MockBookInstanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookInstanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBookInstanceRepositoryMockRecorder is the mock recorder for MockBookInstanceRepository.
type MockBookInstanceRepositoryMockRecorder struct {
	mock *MockBookInstanceRepository
}

// NewMockBookInstanceRepository creates a new mock instance.
func NewMockBookInstanceRepository(ctrl *gomock.Controller) *MockBookInstanceRepository {
	mock := &MockBookInstanceRepository{ctrl: ctrl}
	mock.recorder = &MockBookInstanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookInstanceRepository) EXPECT() *MockBookInstanceRepositoryMockRecorder {
	return m.recorder
}

// DeleteBookInstanceById mocks base method.
func (m *MockBookInstanceRepository) DeleteBookInstanceById(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookInstanceById", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DeleteBookInstanceById indicates an expected call of DeleteBookInstanceById.
func (mr *MockBookInstanceRepositoryMockRecorder) DeleteBookInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookInstanceById", reflect.TypeOf((*MockBookInstanceRepository)(nil).DeleteBookInstanceById), id)
}

// FindBookInstanceById mocks base method.
func (m *MockBookInstanceRepository) FindBookInstanceById(id int) (*book.BookInstance, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBookInstanceById", id)
	ret0, _ := ret[0].(*book.BookInstance)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FindBookInstanceById indicates an expected call of FindBookInstanceById.
func (mr *MockBookInstanceRepositoryMockRecorder) FindBookInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBookInstanceById", reflect.TypeOf((*MockBookInstanceRepository)(nil).FindBookInstanceById), id)
}

// GetBookInstances mocks base method.
func (m *MockBookInstanceRepository) GetBookInstances() ([]*book.BookInstance, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookInstances")
	ret0, _ := ret[0].([]*book.BookInstance)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetBookInstances indicates an expected call of GetBookInstances.
func (mr *MockBookInstanceRepositoryMockRecorder) GetBookInstances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookInstances", reflect.TypeOf((*MockBookInstanceRepository)(nil).GetBookInstances))
}

// GetBookInstancesByISBN mocks base method.
func (m *MockBookInstanceRepository) GetBookInstancesByISBN(isbn string) ([]*book.BookInstance, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookInstancesByISBN", isbn)
	ret0, _ := ret[0].([]*book.BookInstance)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetBookInstancesByISBN indicates an expected call of GetBookInstancesByISBN.
func (mr *MockBookInstanceRepositoryMockRecorder) GetBookInstancesByISBN(isbn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookInstancesByISBN", reflect.TypeOf((*MockBookInstanceRepository)(nil).GetBookInstancesByISBN), isbn)
}

// StoreBookInstance mocks base method.
func (m *MockBookInstanceRepository) StoreBookInstance(bi *book.BookInstance) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StoreBookInstance", bi)
}

// StoreBookInstance indicates an expected call of StoreBookInstance.
func (mr *MockBookInstanceRepositoryMockRecorder) StoreBookInstance(bi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBookInstance", reflect.TypeOf((*MockBookInstanceRepository)(nil).StoreBookInstance), bi)
}

// UpdateBookInstanceById mocks base method.
func (m *MockBookInstanceRepository) UpdateBookInstanceById(id int, updatedBookInstance *book.BookInstance) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookInstanceById", id, updatedBookInstance)
	ret0, _ := ret[0].(bool)
	return ret0
}

// UpdateBookInstanceById indicates an expected call of UpdateBookInstanceById.
func (mr *MockBookInstanceRepositoryMockRecorder) UpdateBookInstanceById(id, updatedBookInstance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookInstanceById", reflect.TypeOf((*MockBookInstanceRepository)(nil).UpdateBookInstanceById), id, updatedBookInstance)
}