// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../../mocks/emailtemplater_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailTemplater is a mock of EmailTemplater interface.
type MockEmailTemplater struct {
	ctrl     *gomock.Controller
	recorder *MockEmailTemplaterMockRecorder
	isgomock struct{}
}

// MockEmailTemplaterMockRecorder is the mock recorder for MockEmailTemplater.
type MockEmailTemplaterMockRecorder struct {
	mock *MockEmailTemplater
}

// NewMockEmailTemplater creates a new mock instance.
func NewMockEmailTemplater(ctrl *gomock.Controller) *MockEmailTemplater {
	mock := &MockEmailTemplater{ctrl: ctrl}
	mock.recorder = &MockEmailTemplaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailTemplater) EXPECT() *MockEmailTemplaterMockRecorder {
	return m.recorder
}

// GetBookingCanceledEmail mocks base method.
func (m *MockEmailTemplater) GetBookingCanceledEmail(reservationId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingCanceledEmail", reservationId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingCanceledEmail indicates an expected call of GetBookingCanceledEmail.
func (mr *MockEmailTemplaterMockRecorder) GetBookingCanceledEmail(reservationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCanceledEmail", reflect.TypeOf((*MockEmailTemplater)(nil).GetBookingCanceledEmail), reservationId)
}

// GetBookingCreatedEmail mocks base method.
func (m *MockEmailTemplater) GetBookingCreatedEmail(reservationId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingCreatedEmail", reservationId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingCreatedEmail indicates an expected call of GetBookingCreatedEmail.
func (mr *MockEmailTemplaterMockRecorder) GetBookingCreatedEmail(reservationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingCreatedEmail", reflect.TypeOf((*MockEmailTemplater)(nil).GetBookingCreatedEmail), reservationId)
}

// GetBookingEndedEmail mocks base method.
func (m *MockEmailTemplater) GetBookingEndedEmail(reservationId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingEndedEmail", reservationId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingEndedEmail indicates an expected call of GetBookingEndedEmail.
func (mr *MockEmailTemplaterMockRecorder) GetBookingEndedEmail(reservationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingEndedEmail", reflect.TypeOf((*MockEmailTemplater)(nil).GetBookingEndedEmail), reservationId)
}

// GetBookingExtendedEmail mocks base method.
func (m *MockEmailTemplater) GetBookingExtendedEmail(reservationId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingExtendedEmail", reservationId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingExtendedEmail indicates an expected call of GetBookingExtendedEmail.
func (mr *MockEmailTemplaterMockRecorder) GetBookingExtendedEmail(reservationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingExtendedEmail", reflect.TypeOf((*MockEmailTemplater)(nil).GetBookingExtendedEmail), reservationId)
}
