// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	book "gotus/internal/model/book"
	message "gotus/internal/model/message"
	reservation "gotus/internal/model/reservation"
	user "gotus/internal/model/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBookRepository is a mock of BookRepository interface.
type MockBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryMockRecorder
	isgomock struct{}
}

// MockBookRepositoryMockRecorder is the mock recorder for MockBookRepository.
type MockBookRepositoryMockRecorder struct {
	mock *MockBookRepository
}

// NewMockBookRepository creates a new mock instance.
func NewMockBookRepository(ctrl *gomock.Controller) *MockBookRepository {
	mock := &MockBookRepository{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRepository) EXPECT() *MockBookRepositoryMockRecorder {
	return m.recorder
}

// DeleteBookByISBN mocks base method.
func (m *MockBookRepository) DeleteBookByISBN(isbn string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookByISBN", isbn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookByISBN indicates an expected call of DeleteBookByISBN.
func (mr *MockBookRepositoryMockRecorder) DeleteBookByISBN(isbn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookByISBN", reflect.TypeOf((*MockBookRepository)(nil).DeleteBookByISBN), isbn)
}

// FindBookByISBN mocks base method.
func (m *MockBookRepository) FindBookByISBN(isbn string) (*book.Book, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBookByISBN", isbn)
	ret0, _ := ret[0].(*book.Book)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindBookByISBN indicates an expected call of FindBookByISBN.
func (mr *MockBookRepositoryMockRecorder) FindBookByISBN(isbn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBookByISBN", reflect.TypeOf((*MockBookRepository)(nil).FindBookByISBN), isbn)
}

// GetBooks mocks base method.
func (m *MockBookRepository) GetBooks() ([]*book.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooks")
	ret0, _ := ret[0].([]*book.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBooks indicates an expected call of GetBooks.
func (mr *MockBookRepositoryMockRecorder) GetBooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooks", reflect.TypeOf((*MockBookRepository)(nil).GetBooks))
}

// StoreBook mocks base method.
func (m *MockBookRepository) StoreBook(b *book.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBook", b)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBook indicates an expected call of StoreBook.
func (mr *MockBookRepositoryMockRecorder) StoreBook(b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBook", reflect.TypeOf((*MockBookRepository)(nil).StoreBook), b)
}

// UpdateBookByISBN mocks base method.
func (m *MockBookRepository) UpdateBookByISBN(isbn string, updatedBook *book.Book) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookByISBN", isbn, updatedBook)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBookByISBN indicates an expected call of UpdateBookByISBN.
func (mr *MockBookRepositoryMockRecorder) UpdateBookByISBN(isbn, updatedBook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookByISBN", reflect.TypeOf((*MockBookRepository)(nil).UpdateBookByISBN), isbn, updatedBook)
}

// MockBookInstanceRepository is a mock of BookInstanceRepository interface.
type MockBookInstanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookInstanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBookInstanceRepositoryMockRecorder is the mock recorder for MockBookInstanceRepository.
type MockBookInstanceRepositoryMockRecorder struct {
	mock *MockBookInstanceRepository
}

// NewMockBookInstanceRepository creates a new mock instance.
func NewMockBookInstanceRepository(ctrl *gomock.Controller) *MockBookInstanceRepository {
	mock := &MockBookInstanceRepository{ctrl: ctrl}
	mock.recorder = &MockBookInstanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookInstanceRepository) EXPECT() *MockBookInstanceRepositoryMockRecorder {
	return m.recorder
}

// DeleteBookInstanceById mocks base method.
func (m *MockBookInstanceRepository) DeleteBookInstanceById(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookInstanceById", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookInstanceById indicates an expected call of DeleteBookInstanceById.
func (mr *MockBookInstanceRepositoryMockRecorder) DeleteBookInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookInstanceById", reflect.TypeOf((*MockBookInstanceRepository)(nil).DeleteBookInstanceById), id)
}

// FindBookInstanceById mocks base method.
func (m *MockBookInstanceRepository) FindBookInstanceById(id int) (*book.BookInstance, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBookInstanceById", id)
	ret0, _ := ret[0].(*book.BookInstance)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindBookInstanceById indicates an expected call of FindBookInstanceById.
func (mr *MockBookInstanceRepositoryMockRecorder) FindBookInstanceById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBookInstanceById", reflect.TypeOf((*MockBookInstanceRepository)(nil).FindBookInstanceById), id)
}

// GetBookInstances mocks base method.
func (m *MockBookInstanceRepository) GetBookInstances() ([]*book.BookInstance, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookInstances")
	ret0, _ := ret[0].([]*book.BookInstance)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookInstances indicates an expected call of GetBookInstances.
func (mr *MockBookInstanceRepositoryMockRecorder) GetBookInstances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookInstances", reflect.TypeOf((*MockBookInstanceRepository)(nil).GetBookInstances))
}

// GetBookInstancesByISBN mocks base method.
func (m *MockBookInstanceRepository) GetBookInstancesByISBN(isbn string) ([]*book.BookInstance, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookInstancesByISBN", isbn)
	ret0, _ := ret[0].([]*book.BookInstance)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookInstancesByISBN indicates an expected call of GetBookInstancesByISBN.
func (mr *MockBookInstanceRepositoryMockRecorder) GetBookInstancesByISBN(isbn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookInstancesByISBN", reflect.TypeOf((*MockBookInstanceRepository)(nil).GetBookInstancesByISBN), isbn)
}

// StoreBookInstance mocks base method.
func (m *MockBookInstanceRepository) StoreBookInstance(bi *book.BookInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBookInstance", bi)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBookInstance indicates an expected call of StoreBookInstance.
func (mr *MockBookInstanceRepositoryMockRecorder) StoreBookInstance(bi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBookInstance", reflect.TypeOf((*MockBookInstanceRepository)(nil).StoreBookInstance), bi)
}

// UpdateBookInstanceById mocks base method.
func (m *MockBookInstanceRepository) UpdateBookInstanceById(id int, updatedBookInstance *book.BookInstance) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookInstanceById", id, updatedBookInstance)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBookInstanceById indicates an expected call of UpdateBookInstanceById.
func (mr *MockBookInstanceRepositoryMockRecorder) UpdateBookInstanceById(id, updatedBookInstance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookInstanceById", reflect.TypeOf((*MockBookInstanceRepository)(nil).UpdateBookInstanceById), id, updatedBookInstance)
}

// MockReservationRepository is a mock of ReservationRepository interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
	isgomock struct{}
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// DeleteReservationById mocks base method.
func (m *MockReservationRepository) DeleteReservationById(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReservationById", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteReservationById indicates an expected call of DeleteReservationById.
func (mr *MockReservationRepositoryMockRecorder) DeleteReservationById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReservationById", reflect.TypeOf((*MockReservationRepository)(nil).DeleteReservationById), id)
}

// FindReservationById mocks base method.
func (m *MockReservationRepository) FindReservationById(id int) (*reservation.Reservation, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReservationById", id)
	ret0, _ := ret[0].(*reservation.Reservation)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindReservationById indicates an expected call of FindReservationById.
func (mr *MockReservationRepositoryMockRecorder) FindReservationById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReservationById", reflect.TypeOf((*MockReservationRepository)(nil).FindReservationById), id)
}

// GetReservations mocks base method.
func (m *MockReservationRepository) GetReservations() ([]*reservation.Reservation, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservations")
	ret0, _ := ret[0].([]*reservation.Reservation)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetReservations indicates an expected call of GetReservations.
func (mr *MockReservationRepositoryMockRecorder) GetReservations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservations", reflect.TypeOf((*MockReservationRepository)(nil).GetReservations))
}

// HasActiveReservation mocks base method.
func (m *MockReservationRepository) HasActiveReservation(bookInstanceID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveReservation", bookInstanceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveReservation indicates an expected call of HasActiveReservation.
func (mr *MockReservationRepositoryMockRecorder) HasActiveReservation(bookInstanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveReservation", reflect.TypeOf((*MockReservationRepository)(nil).HasActiveReservation), bookInstanceID)
}

// StoreReservation mocks base method.
func (m *MockReservationRepository) StoreReservation(r *reservation.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreReservation", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreReservation indicates an expected call of StoreReservation.
func (mr *MockReservationRepositoryMockRecorder) StoreReservation(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreReservation", reflect.TypeOf((*MockReservationRepository)(nil).StoreReservation), r)
}

// UpdateReservationById mocks base method.
func (m *MockReservationRepository) UpdateReservationById(id int, updatedReservation *reservation.Reservation) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReservationById", id, updatedReservation)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReservationById indicates an expected call of UpdateReservationById.
func (mr *MockReservationRepositoryMockRecorder) UpdateReservationById(id, updatedReservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReservationById", reflect.TypeOf((*MockReservationRepository)(nil).UpdateReservationById), id, updatedReservation)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// DeleteUserById mocks base method.
func (m *MockUserRepository) DeleteUserById(id int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserById", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserById indicates an expected call of DeleteUserById.
func (mr *MockUserRepositoryMockRecorder) DeleteUserById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserById", reflect.TypeOf((*MockUserRepository)(nil).DeleteUserById), id)
}

// FindUserByEmail mocks base method.
func (m *MockUserRepository) FindUserByEmail(email string) (*user.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockUserRepositoryMockRecorder) FindUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindUserByEmail), email)
}

// FindUserById mocks base method.
func (m *MockUserRepository) FindUserById(id int) (*user.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserById", id)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindUserById indicates an expected call of FindUserById.
func (mr *MockUserRepositoryMockRecorder) FindUserById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserById", reflect.TypeOf((*MockUserRepository)(nil).FindUserById), id)
}

// GetUsers mocks base method.
func (m *MockUserRepository) GetUsers() ([]*user.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers")
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockUserRepositoryMockRecorder) GetUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUserRepository)(nil).GetUsers))
}

// StoreUser mocks base method.
func (m *MockUserRepository) StoreUser(u *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUser", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreUser indicates an expected call of StoreUser.
func (mr *MockUserRepositoryMockRecorder) StoreUser(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUser", reflect.TypeOf((*MockUserRepository)(nil).StoreUser), u)
}

// UpdateUserById mocks base method.
func (m *MockUserRepository) UpdateUserById(id int, updatedUser *user.User) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserById", id, updatedUser)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserById indicates an expected call of UpdateUserById.
func (mr *MockUserRepositoryMockRecorder) UpdateUserById(id, updatedUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserById", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserById), id, updatedUser)
}

// MockEmailMessage is a mock of EmailMessage interface.
type MockEmailMessage struct {
	ctrl     *gomock.Controller
	recorder *MockEmailMessageMockRecorder
	isgomock struct{}
}

// MockEmailMessageMockRecorder is the mock recorder for MockEmailMessage.
type MockEmailMessageMockRecorder struct {
	mock *MockEmailMessage
}

// NewMockEmailMessage creates a new mock instance.
func NewMockEmailMessage(ctrl *gomock.Controller) *MockEmailMessage {
	mock := &MockEmailMessage{ctrl: ctrl}
	mock.recorder = &MockEmailMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailMessage) EXPECT() *MockEmailMessageMockRecorder {
	return m.recorder
}

// InsertMessage mocks base method.
func (m_2 *MockEmailMessage) InsertMessage(m *message.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "InsertMessage", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMessage indicates an expected call of InsertMessage.
func (mr *MockEmailMessageMockRecorder) InsertMessage(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMessage", reflect.TypeOf((*MockEmailMessage)(nil).InsertMessage), m)
}
