// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../mocks/reservation_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reservation "gotus/internal/model/reservation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReservationRepository is a mock of ReservationRepository interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
	isgomock struct{}
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// DeleteReservationById mocks base method.
func (m *MockReservationRepository) DeleteReservationById(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReservationById", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DeleteReservationById indicates an expected call of DeleteReservationById.
func (mr *MockReservationRepositoryMockRecorder) DeleteReservationById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReservationById", reflect.TypeOf((*MockReservationRepository)(nil).DeleteReservationById), id)
}

// FindReservationById mocks base method.
func (m *MockReservationRepository) FindReservationById(id int) (*reservation.Reservation, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReservationById", id)
	ret0, _ := ret[0].(*reservation.Reservation)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FindReservationById indicates an expected call of FindReservationById.
func (mr *MockReservationRepositoryMockRecorder) FindReservationById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReservationById", reflect.TypeOf((*MockReservationRepository)(nil).FindReservationById), id)
}

// GetReservations mocks base method.
func (m *MockReservationRepository) GetReservations() ([]*reservation.Reservation, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservations")
	ret0, _ := ret[0].([]*reservation.Reservation)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetReservations indicates an expected call of GetReservations.
func (mr *MockReservationRepositoryMockRecorder) GetReservations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservations", reflect.TypeOf((*MockReservationRepository)(nil).GetReservations))
}

// HasActiveReservation mocks base method.
func (m *MockReservationRepository) HasActiveReservation(bookInstanceID int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveReservation", bookInstanceID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasActiveReservation indicates an expected call of HasActiveReservation.
func (mr *MockReservationRepositoryMockRecorder) HasActiveReservation(bookInstanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveReservation", reflect.TypeOf((*MockReservationRepository)(nil).HasActiveReservation), bookInstanceID)
}

// StoreReservation mocks base method.
func (m *MockReservationRepository) StoreReservation(r *reservation.Reservation) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StoreReservation", r)
}

// StoreReservation indicates an expected call of StoreReservation.
func (mr *MockReservationRepositoryMockRecorder) StoreReservation(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreReservation", reflect.TypeOf((*MockReservationRepository)(nil).StoreReservation), r)
}

// UpdateReservationById mocks base method.
func (m *MockReservationRepository) UpdateReservationById(id int, updatedReservation *reservation.Reservation) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReservationById", id, updatedReservation)
	ret0, _ := ret[0].(bool)
	return ret0
}

// UpdateReservationById indicates an expected call of UpdateReservationById.
func (mr *MockReservationRepositoryMockRecorder) UpdateReservationById(id, updatedReservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReservationById", reflect.TypeOf((*MockReservationRepository)(nil).UpdateReservationById), id, updatedReservation)
}